#debug: true
logging:
    level:
        com:
            example:
                demo:
                    dao: info
        org:
            springframework:
                web: info
        root: info
mybatis:
    mapperLocations: classpath:mapper/*.xml
server:
    tomcat:
        uri-encoding: UTF-8
spring:
    datasource:
        driver-class-name: oracle.jdbc.driver.OracleDriver
        initialSize: 5
        maxActive: 20
        maxPoolPreparedStatementPerConnectionSize: 20
        maxWait: 10000
        minIdle: 5
        password: password
        poolPreparedStatements: true
        testWhileIdle: true
        timeBetweenEvictionRunsMillis: 60000
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:oracle:thin:@172.16.14.155:1521:orcl
        username: HCZZPPolSituInfo
        validationQuery: SELECT 'x' from dual
    druid:
    # 是否启用StatFilter配置
      web-stat-filter:
        enable: true
      monitor:
        # 多个白名单IP用逗号分隔
        allow: 127.0.0.1
        # 多个黑名单IP用逗号分隔
        deny: 0.0.0.0
        loginUsername: jsong
        loginPassword: neusoft
        # 是否开启重置功能
        resetEnable: false
    http:
        encoding:
            charset: UTF-8
            enabled: true
            force: true
    message:
        encoding: UTF-8
    redis:
        database: 0
        host: 127.0.0.1
        pool:
            max-active: 100
            max-idle: 10
            max-wait: -100000
            min-idle: 0
        port: 6379
        timeout: 0
    data:
        elasticsearch:
            cluster-name: elasticsearch
            cluster-nodes: 127.0.0.1:9300
            repositories:
                enabled: true
swagger:
    basePackage: com.example.demo.controller
    description: 服务端接口
    title: 测试服务
    version: 版本V1.0
